### ISSUE TITLE
Alignment with the "Alliance for Parking Data Standards"

### ISSUE THREAD

**Issue by sharrop** [smart-data-models/dataModel.Parking#1]
Are you aware of the Alliance for Parking Data Standards?
https://www.allianceforparkingdatastandards.org/

I am not affiliated, and have no access to the details, but I remembered its announcement from 30-May 2019, and thought it might be worthy of alignment:

"The Alliance for Parking Data Standards (APDS), formed by the International Parking & Mobility Institute (IPMI), the British Parking Association (BPA), and the European Parking Association (EPA), is a not-for-profit organization with the mission to develop, promote, manage, and maintain a uniform global standard that will allow organizations to share parking data across platforms worldwide."

**Comment by albertoabellagarcia** [comment]
Thank you very much for this issue. We've requested the standards. (A bit weird that if you want the standards to spread you do not have them publicly available).
We'll take that into account. 
If you want further involvement regarding this data model please let me know.
