### ISSUE TITLE
Error wrapping lines in the generation of example.jsonld

### ISSUE THREAD

**Issue by danielvillalbamota** [smart-data-models/dataModel.Parking#11]
https://github.com/smart-data-models/dataModel.Parking/blob/3c7393a7603edc9b97904c38e47eedb8b1ed593b/OffStreetParking/examples/example.jsonld#L15-L16

It seems to have an error when the script that automate the generation of examples wrap lines. It separates the text in a new line and include ending and starting quotation marks when it should not. This does not occurs in others examples (.json or normalized)

**Comment by albertoabellagarcia** [comment]
Thanks. fixed
