### ISSUE TITLE
incorrect documentation on the allowed values of allowedVehicleType (VehicleTypeEnum)

### ISSUE THREAD

**Issue by jpnbastos** [smart-data-models/dataModel.Parking#13]
We will be using the OnStreetParking datamodel.
According to the documentation, the allowedVehicleType attribute allows values defined by VehicleTypeEnum a DATEX 2 version 2.3. 

There seems to be a mismatch:

-  On the [OnStreetParking documentation](https://fiware-datamodels.readthedocs.io/en/latest/Parking/OnStreetParking/doc/spec/index.html) the value `twoWheeledVehicle` is not an allowed value of `allowedVehicleType` which is of type **VehicleTypeEnum**.

- However, on the [DATEX 2 documentation](https://docs.datex2.eu/_static/umlmodel/v2.3/index.htm?goto=2:3:6:320) it seems that **VehicleTypeEnum** does indeed include `twoWheeledVehicle`.

Can we assume that this is a simple documentation issue? If so can this be corrected? I can also do this if we agree on it 👍

**Comment by albertoabellagarcia** [comment]
You're right, not only this value was missing some other as well. Additionally, the schema.json was also updated to meet the spec.md.
