### ISSUE TITLE
a field to store information about occupied spots (e.g. occupiedSpotNumber)

### ISSUE THREAD

**Issue by jpnbastos** [smart-data-models/dataModel.Parking#15]
While developing an application that processed entities stored as OnStreetParking, we noticed that we can store the information about the total number of spot and the available number of parking spots.

Our application is mainly concerned about showing the current occupancy of the parking area. Which we are computing as the number of vehicles located in that OnStreetParking. 

We solved this currently by making Available = Total - Occupied. However, this as a few downfalls:

- In our case sometimes more vehicles are parked than there are spots available, so Available becomes a negative number.
- If the parking capacities are updated then we must also take care of accordingly updating the Available field, which if not accounted for can lead to faulty issues.

For this reason, we wanted to know if it is possible to add an extra optional field to the datamodel such as occupiedSpotNumber? 

Thanks :)

**Comment by albertoabellagarcia** [comment]
it is possible as long as the rest of the contributors do not show objections. Anyhow the licence of the data models allows you to do it always.

**Comment by albertoabellagarcia** [comment]
not seeing incoveniences, could you launch a PR?

**Comment by jpnbastos** [comment]
Okay, we will do so :)

**Comment by jpnbastos** [comment]
What is the current flow for a PR? Do I open a branch from this repo? Do I need permission?

I have the code ready.

**Comment by albertoabellagarcia** [comment]
I see that you have already created the PR. Let us review it. thanks
