### ISSUE TITLE
Swagger yml for onStreetParking doesnt include the newly added attribute 'occupiedSpotNumber'

### ISSUE THREAD

**Issue by jaimeventura** [smart-data-models/dataModel.Parking#19]
Following #17, when accessing the [interactive specification](https://swagger.lab.fiware.org/?url=https://smart-data-models.github.io/dataModel.Parking/OnStreetParking/swagger.yaml) the added attribute 'occupiedSpotNumber' is not present.

**Comment by albertoabellagarcia** [comment]
Thanks for noticing. 
Fixed
