### ISSUE TITLE
onStreetParking permitActiveHours schema

### ISSUE THREAD

**Issue by modularTaco** [smart-data-models/dataModel.Parking#20]
Hey,

the description of `permitActiveHours` in the `OnStreetParking` schema mentions that `The syntax must be conformant with schema.org`, but it does not mention which schema.org Property it needs to be conformant with.  
From the example `"blueZonePermit": "Mo, Tu, We, Th, Fr, Sa 09:00-20:00"` i guess https://schema.org/openingHours is used. Am i right here?

If `openingHours` is used, is there any possibility to specify special  `permitActiveHours` for holidays?  
If not, maybe it's worth considering the usage of https://schema.org/openingHoursSpecification as a more expressive alternative to `openingHours`, which allows the `dayOfWeek` to be `PublicHolidays`.

**Comment by albertoabellagarcia** [comment]
That's a nice thing. Do you have a use case for that? Both alternatives are possible. The one used is the one preferred. In fact https://schema.org/openingHoursSpecification is replicated in the commons-schema.json of the overall alternative and it's been used in other data models.

**Comment by modularTaco** [comment]
We're currently investigating how we want do model our parking zones in order to import them to Orion.  
As i've not received the parking zones data yet i don't know if we really need the implementation of public holidays, but it was part of our internal discussion and i thought others could benefit from it to if it would be used in this datamodel.

>Both alternatives are possible.
Does this mean that the current version of the datamodel does not make any assumption if `openingHours` or `openingHoursSpecification` is used and both would valid currently?

**Comment by albertoabellagarcia** [comment]
So then, let me close the issue and please reopen it when you have the information about the zones and what will be the criteria for using one of the alternatives.
thanks a lot
