### ISSUE TITLE
Should OnStreetParking's allowedVehicleType be a single value instead of an array?

### ISSUE THREAD

**Issue by Nanner** [smart-data-models/dataModel.Parking#21]
Hello everyone,

In the schema for the `OnStreetParking` model, the `description` for the `allowedVehicleType` attribute mentions "Vehicle type allowed **(only one per on street parking)**". However, this attribute is defined as an array of values, instead of a single value.

The old Fiware Datamodel documentation used to describe this attribute as a Text value instead of List of Text, if I'm not mistaken. Is this just an outdated description for the updated model, or should this field still only allow for a single value? The description for the same attribute in the `OffStreetParking` model, on the other hand, does mention it can hold multiple values.

Thank you very much in advance and I apologize for any misunderstanding on my end. Have a good day!

**Comment by albertoabellagarcia** [comment]
Thank you. 
It has to be an array, like in offstreetparking.

Already fixed

thanks

**Comment by jpnbastos** [comment]
I think the description has not been changed yet because we were having similar doubts and only this closed issue solved it :) the array solution is perfect!

**Comment by jpnbastos** [comment]
I will make a proposal on a PR if it helps

**Comment by albertoabellagarcia** [comment]
the schema was changed, but we forgot for the spec (I guess it possibly throws some unnoticed error).

**Comment by albertoabellagarcia** [comment]
running the update

**Comment by albertoabellagarcia** [comment]
I can confirm that there is an issue, that only affects the English translation... (the other languages' specs seem to be right)

**Comment by albertoabellagarcia** [comment]
I guess that it is a problem of the unbearable delay between an update of a file and the availability of the raw version on github. we run the script after the update but the raw version is not updated. Thus, it seems that the script did not worked while we need is to wait some minutes?? till this is updated.
