### ISSUE TITLE
missing location Attribut in ParkingGroup

### ISSUE THREAD

**Issue by FR-ADDIX** [smart-data-models/dataModel.Parking#22]
in schema.json the reference to Location Commons is missing.

    {
      "$ref": "https://smart-data-models.github.io/data-models/common-schema.json#/definitions/Location-Commons",
      "description": "All from Location-Commons [https://smart-data-models.github.io/data-models/common-schema.json#/definitions/Location-Commons](https://smart-data-models.github.io/data-models/common-schema.json#/definitions/Location-Commons)"
    },

**Comment by albertoabellagarcia** [comment]
you're right
updated..
thanks
