### ISSUE TITLE
Wrong observationDateTime in OnStreetParking and OffstreetParking examples ?

### ISSUE THREAD

**Issue by fbattello** [smart-data-models/dataModel.Parking#23]
Hi,

The `observationDateTime` property has this value : `"2021-03-11T15:51:02+05:30"`.

It seems to be disaligned with the other datetimes in the entity that all refer to `"2018-09-21T12:00:00Z"`, for example the `observedAt` property of `availableSpotNumber`.

Always speaking about `observationDateTime` but this time about its format.
Should it be converted to "2021-03-11T10:21:02Z" according to the ETSI specification that restricts timezones to UTC *in my comprehension* ?

**Comment by albertoabellagarcia** [comment]
you're right.

fixed
