### ISSUE TITLE
Typo "Geoproperty" instead of "GeoProperty" in the location property of OnStreetParking and OffStreetParking examples

### ISSUE THREAD

**Issue by fbattello** [smart-data-models/dataModel.Parking#24]
Hi,

Noticed it as the broker complained when trying to persist the OffStreetParking example.

**Comment by albertoabellagarcia** [comment]
You got us! Fully right. 
The worse thing is that you have detected this in one place but we have detected this error in several others. 
so thank you very much

**Comment by albertoabellagarcia** [comment]
Launching a script to correct this typo across all data models... it will take a while, 1-2 hours .
thanks
