### ISSUE TITLE
"iudx:SmartParking" part of the context in the OffStreetParking example, but not in OnStreetParking

### ISSUE THREAD

**Issue by fbattello** [smart-data-models/dataModel.Parking#25]
Hi,

`"iudx:SmartParking"` is present in the context of the OffStreetParking example.
Is this normal ?

The broker *- in my case Orion-LD -* refuses - for that reason - to persist the OffStreetParking example.
It seems that it hasn't been able to resolve the uri.
Showing me this error message : `NgsiInternalError: Timeout during download of an @context : iudx:SmartParking`.
After removing it from the context, I can persist the entity in the broker.

Strangely this `"iudx:SmartParking"` part of the context is not present in the OnStreetParking example.

**Comment by albertoabellagarcia** [comment]
This is an actual example, so they use what they need. Examples are there for illustrative reasons, and the internal configuration of their systems, like adding additional context sources is possible. You can remove it definitely. 

We create a @context always in the root of the subject. Visit it here
[https://github.com/smart-data-models/dataModel.Parking/blob/master/context.jsonld](https://github.com/smart-data-models/dataModel.Parking/blob/master/context.jsonld) 

But you can use anything you want, and in fact we have two tools at [smartdatamodels.org](https://smartdatamodels.org) to help you with that

Home -> tools-> [Mapper @context with external ontologies](https://smartdatamodels.org/index.php/generate-acontext-based-on-external-ontologies-iris/) for mapping the terms of the SDM with external ontologies. 
Home -> tools -> [Subjects' @context merger](https://smartdatamodels.org/index.php/generate-a-local-context-based-on-smart-data-models-iris/) for merging several @contexts coming from different subjects.
