### ISSUE TITLE
Make the OffStreetParking example broker-compatible

### ISSUE THREAD

**Issue by fbattello** [smart-data-models/dataModel.Parking#26]
Hi,

I keep on developing [python-ngsild-client](https://github.com/Orange-OpenSource/python-ngsild-client), a Python library that allows to create and modify NGSI-LD entities effortlessly, and to interact with a NGSI-LD broker.

The Getting Started chapter uses the `OffStreetParking` normalized example to showcase how one can manipulate a complex Entity and persist it into the broker.
But unfortunately the `udx:SmartParking` context is not resolved by the broker then prevents the parking to be persisted.
I've added this minor fix.

```python
from ngsildclient import Client, Entity, SmartDataModels

parking = Entity.load(SmartDataModels.SmartCities.Parking.OffStreetParking)
parking.ctx.remove("iudx:SmartParking")  # the fix !

client = Client()  # assumes that a local broker instance is running (localhost, default port=1026)
client.create(parking)  # ok
```

But it would be nice to be able to persist the example "as-is".
Would you mind removing this part of the context ?
Or if it's not possible maybe do you know a way to tell a broker to ignore a specific context ?

**Comment by albertoabellagarcia** [comment]
We've removed the elements of the @context that were not resolved. They came from the example which possibly has an additional @context entry.
Thanks for the warning
