### ISSUE TITLE
Question regarding the refParkingSite property of the ParkingGroup data model

### ISSUE THREAD

**Issue by thanospan** [smart-data-models/dataModel.Parking#29]
According to the ParkingGroup data model, refParkingSite is a reference to an OffStreetParking or OnStreetParking entity. In the NGSI-LD examples, shouldn't the property refParkingSite have a value of "urn:ngsi-ld:OnStreetParking:daoiz-velarde-1-5" instead of "urn:ngsi-ld:ParkingSite:daoiz-velarde-1-5" (since the category of "urn:ngsi-ld:ParkingGroup:daoiz-velarde-1-5-disabled" is "onStreet")?

**Comment by albertoabellagarcia** [comment]
Yes, it is a good practice to do it the way you mentioned. And the provider of the example should do this for having a healthy system. 
But, is it mandatory? No, you can call your categories whatever you want even if this can lead you to make mistakes about the nature of the object you are pointing to.
