### ISSUE TITLE
Level of a parking spot in an offstreet parking

### ISSUE THREAD

**Issue by tarswars** [smart-data-models/dataModel.Parking#30]
There is currently no easy way to indicate the level of a parking spot in an offstreet parking garage.

Could this field be added to the parking spot data model?

Some notes I can think of:
* It should not be mandatory since for most onstreet parkings, a level will not be applicable.
* This should be a string, since levels could be non-numerical as there can be half floors or other exceptions. Eg "1a"

**Comment by albertoabellagarcia** [comment]
Thank you for the issue, only those attributes listed in the required clause are mandatory attributes.

But in order to extend the model we need you to share also an example of a payload coming from a real case.
Please make a PR with the modifications of the schema.json and the new example. 
Thanks
