### ISSUE TITLE
Updating to latest version of standardised parking model

### ISSUE THREAD

**Issue by JHB9876** [smart-data-models/dataModel.Parking#32]
The DATEX II parking publications data model was revised and published in 2022.  This largely aligns to the Alliance for Parking Data Standards (APDS) specification, which is also represented in ISO TS 5206-1:2023. Can this content be updated?

**Comment by albertoabellagarcia** [comment]
Definitely can be updated but we need an example of its adoption. We'll be glad to receive a PR with that.

**Comment by JHB9876** [comment]
The UK Department for Transport is funding the pilot of is slated to be a National Parking Platform.  See https://npp-uk.org/ for further information.  The NPP is based on the APDS specifications.  

The APDS specifications are available from : https://www.allianceforparkingdatastandards.org/
The APDS API specifications are published at: https://github.com/parkingdata/spec

**Comment by albertoabellagarcia** [comment]
We have explored it. It is too broad and we need help. Is there any source of information about the schemas that it was not an image in a pdf file (a json schema or other technical source?)

**Comment by albertoabellagarcia** [comment]
Glad to reopen the issue when some support is found
