### ISSUE TITLE
extCategory property missing definition

### ISSUE THREAD

**Issue by danielvillalbamota** [smart-data-models/dataModel.Parking#5]
The "extCategory" property of OffStreetParking is defined in the [schema.json](https://github.com/smart-data-models/dataModel.Parking/blob/6fd6e62da87962b9743eea36c2857d7226f4e0a7/OffStreetParking/schema.json) but not explained in the README nor used in examples. There is not definition of its use.

Should it be defined or removed?

**Comment by albertoabellagarcia** [comment]
No it should't be removed but you are definitely right. We have already fixed the payload examples. But it'll take a while with the spec. 
We have decided to change the spec.md format and therefore we'll do most of them brand new (at the same time).
[PR](https://github.com/smart-data-models/dataModel.Parking/tree/master/OffStreetParking) is already merged. 
thanks

**Comment by albertoabellagarcia** [comment]
If you want to be updated on these data models you can subscribe [here](http://data-models.fiware.org/) option smart Cities
or just visit this link [http://data-models.fiware.org/index.php/category/smart-cities/](http://data-models.fiware.org/index.php/category/smart-cities/)
